title: "Bini Teklehaimanot"
description: "Principal Data Scientist | High-stakes decision systems in healthtech and fintech"
url: "https://btexpress1.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.27.3"

plugins:
  - jekyll-include-cache

# Minimal Mistakes settings
locale: "en-US"
name: "Bini Teklehaimanot"
repository: "BTExpress1/btexpress1.github.io"

