project:
  type: website

website:
  title: ""   # hide text title
  navbar:
    logo: assets/images/logo.png
    collapse: false
    right:
      - text: "About"
        href: about.qmd
      - text: "Case Studies"
          href: case-studies/index.qmd
      - text: "Philosophy"
        href: philosophy/index.qmd
      - text: "Blog"
        href: blog/index.qmd



format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    smooth-scroll: true
